accentor/api

app/controllers/albums_controller.rb
app/controllers/artists_controller.rb

This reduces the total request time for albums and artists drastically (up to 3x speedup, when testing with our production database).

Avoid n+1 queries when getting ActiveStorage blobs

---

.rubocop.yml

I checked the logs of the dependabot update before merging, but the warning about the new cops wasn't shown there. This PR adds their configuration.

Configure new cops

---

app/controllers/application_controller.rb

Tiny fix.
We have these keys under the plural in [web](https://github.com/accentor/web/blob/70f09d2419866f87c0d95c52d94777aa51e6378c/src/locales/nl.json#L84), since the singular was already user to name the model in errors.

Send not-found errors with modelname in plural

---

app/models/rescan_runner.rb

Limit the lenght of the backtrace for RescanRunner errors in production
Tested locally to produce the correct errors in prod/dev env

Don't include full backtrace of error in prod

---

config/storage.yml

This should improve caching behaviour.
Should fix #24.
No tests, but I did run locally.

Make storage definitions public for image permalinks

---

.github/workflows/ci.yml

The action to setup ruby from the ruby org:
* Supports a lot more rby versions
* Handles bundler install and cache for dependencies
* Read the version from /.ruby_version, so our actions don't need to be updated when we update a ruby version
* (and is just as fast)

Switch ruby setup in CI to action from ruby org

---

Gemfile
config/routes.rb
lib/tasks/auto_annotate_models.rake

Since rails 6.1 the rake commen to generate routes if no longer available, but the annotate gem still depends on this task.
This PR applies a small workaround, that we can keep until annotate is updated.

Fix annotate route generation

---

.github/release-drafter.yml
.github/workflows/release.yml

You can see an example in the latest android release: https://github.com/accentor/android/releases/tag/v0.3.0

Add GitHub action to automatically create a release when a tag is pushed

---

app/models/rescan_runner.rb

This PR changes the way a track's artists are set from the file's metadata during a rescan. Previously, we would not set a composer if the content of the composer field was equal to the content of the artist field. After this change, we always set the composer if the tag is present.
There are two reasons for this change:
1. The behaviour of the rescan becomes easier to comprehent. If a tag is present in the file, it will show up. The current behaviour can cause situations that are confusing to a user who is not familiar with the code. (For example, when some tracks on an album have the same composer and artists and others don't; or when some tracks have a misspelling of the composer/artist's name).
2. This sort of "fixes" should be handled while editing. The review comments, that are …

Always add composer from track's metadata

---

app/controllers/albums_controller.rb
app/controllers/artists_controller.rb
test/controllers/albums_controller_test.rb
test/controllers/artists_controller_test.rb

I noticed that we currently aren't able to remove an image (only replace it), while working on Accentor/web#563
It shouldn't occur often, but we should probably provide this option. 
With the PR images can be reset if the params for an album/artist include `image: { data: nil }`. This way the image is only removed if we are very explicit about it, if `image: nil` is used nothing happens.

Allow images to be removed

---

config/initializers/version.rb

This PR does two things:
* Adds the application version in an initializer, so it can be used inside the application
* Adds an extra header to the default headers, with the version. (Which will be helpful when debugging in production or if we ever need to handle breaking changes in web/android)
A test didn't really seem relevant, but we can always test that the header is present in a random request

Set version inside application and add to headers

---

app/models/location.rb
test/models/location_test.rb

Re #254
I've changed the validation to actually use the pathname. Since this requires us to actually load the locations from the database, so I've merged the two validations into one, so we only have to do the iteration over the locations once.
This also has the benefit that relative paths will be expanded before the check happens - but I wouldn't immediatly know how to write a test for this.

Make sure we allow two sibling dirs

---

db/migrate/20210905090539_add_location_to_rescan_runner.rb

The migration didn't work, because `destroy_all` went looking for the relevant location (since there is a `belongs_to` in the model).

Fix migration for rescan runner per location

---

app/controllers/tracks_controller.rb
app/models/track_artist.rb
app/policies/track_policy.rb
app/serializers/track_artist_serializer.rb
db/migrate/20211127114919_add_hidden_to_track_artists.rb
db/schema.rb
test/factories/track_artists.rb
test/models/track_artist_test.rb

Allows mod+ to "hide" a TrackArtist. This way, detailed credits can be added to a song, while the main overviews will stay minimal (if that is what is wanted for a track).
No additional tests added - since I couldn't think of a relevant test here.

Add hidden attribute to TrackArtist

---

app/models/album.rb
app/models/application_record.rb
app/models/artist.rb
app/models/track.rb
test/models/album_test.rb
test/models/artist_test.rb
test/models/track_test.rb

This PR adds a method to define which values should be nullified if they are blank.
We want to have control over which columns should be normalized, since some columns (`AlbumArtist.separator`) can explicitly be an empty string but not nil.
I've currently added the Album's edition_description and all instances of the review_comment.
Fixes #316 
This PR currently doesn't include way to fix this for all current places where the empty string is present. Should we leave this up to the user to fix (in the interface or console), or add a migration to go over all albums, artists and tracks.
I've currently included this method in `ApplicationRecord`, but could also see this being a concern that should be explicitly included in each model

Nilify empty strings

---

config/database.yml

In my local development setup I've been switching to a postgres instance per project, which runs in `tmp/postgres`.
To easily use this database, I'd like to set the database_host through an ENV variable. (I could also do this with a database_url, but this requires the variable to be URI encoded, where the host can be a regular path. It's just a bit easier to set `/path/to/accentor/api/tmp/postgres` rather than `postgres://%2fpath%2fto%2faccentor%2fapi%2ftmp%2fpostgres/accentor_development`)
Since I added the fallback to localhost, this should not cause any difference to other users. [Due to the way Rails' connection preference works](https://guides.rubyonrails.org/configuring.html#connection-preference), this also should not cause a difference for people who currently use the DATABASE_URL …

Allow database_host to be specified through ENV var

---

config/database.yml

This PR fixes a bug introduced in #319 
In production environments setting a `DATABASE_URL` variable with a unix socket, an error could occur where the database didn't allow connections:
```
PG::ConnectionBad: fe_sendauth: no password supplied
Caused by:
ActiveRecord::ConnectionNotEstablished: fe_sendauth: no password supplied
```
This seems to be caused by the way rails merges the URL variable with the config (instead of overwritten the whole config).
Since we only need a `DATABASE_HOST` variable in the development and test env - and it's generally recommended to set `DATABASE_URL` in production - I've simply moved the added config to those two environments.

Only specify database host for development and test

---

.gitattributes
.github/workflows/dependencies.yml
README.md
flake.lock
flake.nix
gemset.nix

re Accentor/flake#5
This PR:
* Adds a flake.nix that exposes the api package and a devshell
* Adds a github action to automatically keep gemset.nix in sync (after dependabot or if people don't use nix).
Might be good if this can be tried on different machines and OS's (I only have aarch64-darwin).
The devshell can be used with `nix develop` or `use flake` inside an `.envrc`-file.
It will print out a message with some of the additional commands:
```
🔨 Welcome to Accentor API
[database]
pg:console - Open database console
pg:setup   - Setup postgres in project folder
pg:start   - Start postgres instance
pg:stop    - Stop postgres instance
[general commands]
menu       - prints this menu
```
If we want to, we can customize this message.
The `pg:*` commands allow us to keep the database fully …

Add nix flake with devshell and package

---

app/models/rescan_runner.rb

If an audio file contained a date tag with an empty string, we would run into the following error
```
An error occurred while processing /path/to/file.flac: invalid year (not numeric)
/app/models/rescan_runner.rb:203:in `initialize'
/app/models/rescan_runner.rb:203:in `new'
/app/models/rescan_runner.rb:203:in `convert_year'
/app/models/rescan_runner.rb:95:in `process_file'
/app/models/rescan_runner.rb:72:in `block (2 levels) in process_all_files
```
We now check `if tag.blank?` so both `nil` and empty strings are captured
No tests added, since my tag editor doesn't allow me to add dates with empty strings 🤷

Only process date tag if it is present

---

app/models/album.rb
app/models/rescan_runner.rb
app/serializers/album_serializer.rb
db/migrate/20220430121719_change_null_album_release.rb
db/schema.rb
test/controllers/albums_controller_test.rb
test/factories/albums.rb
test/models/album_test.rb

Fixes #323
In this PR I:
* Added not null and a default to the Album's `release` column
* Updated the factory and the usage of the albums factory
* Remove the default value of the release date in the rescan runner

Enforce album release date

---

.github/workflows/cachix.yml
.github/workflows/update.yml
flake.lock

Successful run of the Cachix action (without the `branches: [ main ]` selector) can be found [here](https://github.com/accentor/api/actions/runs/2364245278).
Support for aarch64-darwin can be added in the near future if I understand [this](https://github.com/actions/runner/issues/805#issuecomment-1132966327) correctly.

Add actions to update flake.lock and build derivations

---

.github/workflows/update.yml

The current system to update the flake dependencies somehow picked me as the author of the commits ([example](https://github.com/accentor/api/commit/36a7b0f4c2d2fe183d696f6469bd3c920d554ae1)). This is a bit confusing 😅 
I propose to always attribute these changes [accentor-bot](https://github.com/accentor-bot)

Attribute automated commits to accentor bot

---

flake.nix

Re #337 
Adds an extra command `gems:update` to the devshell, so a user can easily bring the `Gemfile.lock` and `gemset.nix` up to date with the `Gemfile`.
I've also removed bundix from the packages exposed in the devshell, since I would recommend flake users to use this command.
Tested locally by adding a new gem to the gemfile and verifying that everything works

Add command to auto-update `Gemfile.lock` and `gemset.nix`

---

app/controllers/tracks_controller.rb

The ETag calculation was still happening, so somewhat slow
responses (e.g. transcodes of an hour of music) could take a minute until first
byte sent. This means that clients time out when trying to stream these files.
Related: #215 #216

Fix responses not being streamed

---

app/controllers/playlists_controller.rb
app/models/album.rb
app/models/artist.rb
app/models/playlist.rb
app/models/playlist_item.rb
app/models/track.rb
app/models/user.rb
app/policies/playlist_policy.rb
app/serializers/playlist_serializer.rb
config/routes.rb
db/migrate/20220327115559_create_playlists.rb
db/migrate/20220327120150_create_playlist_items.rb
db/schema.rb
test/controllers/playlists_controller_test.rb
test/factories/playlist_items.rb
test/factories/playlists.rb
test/models/artist_test.rb
test/models/playlist_item_test.rb
test/models/playlist_test.rb
test/models/track_test.rb

This PR adds a basic implementation of Playlists and exposes this through the API.
The concept of a Playlist is currently the following:
* A playlist is a collection of either albums, artists or tracks. All items within one playlist should be of the same type.
This allows us to create playlist like 'My favorite songs', 'My top 10 albums of 2022', 'All artists playing at festival X'
* The items in a playlist are ordered (though a user can choose to not use this).
* A playlist is either personal or shared. A personal playlist can only be updated or destroyed by the user it belongs to, a shared playlist can be updated all the users.
My primary reasoning for this distinction is for subjective and objective lists. 'Robbe's top 10 ambient albums' would be a personal list. 'All artists playing …

Add playlists and playlist items

---

app/models/playlist.rb
test/models/playlist_test.rb

Fixes #351 
Our current way of setting the `items` through `item_ids` required some changes to make sure that it runs after the full playlist is modified. I've left some comments to explain the behaviour for ourselves in the future.
Matching PR in web will follow asap.

Return error when creating double playlist items

---

config/application.rb
config/initializers/active_storage.rb

Fixes https://github.com/accentor/android/issues/399.

Cache activestorage images forever

---

flake.nix

Moving the compilation to the buildPhase gives a small improvement when booting the app. The cache now gets compiled to a folder outside of the nix store during boot (or afterwards if code changes), but since the application's code can't change after build, the cache should also never change.
I've been using this change in some other rails apps, and this seems to work without much problems.

Precompile bootsnap during `buildPhase`

---

.github/workflows/cachix.yml
.github/workflows/dependencies.yml
.github/workflows/update.yml

Passing the `GITHUB_TOKEN` to `cachix/install-nix-action` should fix our actions failing due to github's rate limiting.

Pass github token to `install-nix-action`

---

.github/workflows/cachix.yml
.github/workflows/dependencies.yml
.github/workflows/update.yml

Followup on #417 
The current release of `install-nix-action` does not yet support the `github_access_token` input. 
I've now pinned this action to the last commit (the other option would be to pin to the `main` branch), since this includes those changes

Pin `install-nix-action` to specific commit

---

app/models/artist.rb
test/models/artist_test.rb

Fixes #346
With this PR, we will keep the image of an artist during merging, if the artist we are merging into doesn't have an image yet.

Keep image during merge of two artists

---

app/controllers/albums_controller.rb
app/models/album.rb
app/policies/album_policy.rb
config/routes.rb
test/controllers/albums_controller_test.rb
test/models/album_test.rb

Since we have playlists, it has become relevant to merge albums.
We currently simply move over the tracks, playlist items and image (if the target does not yet have an image itself). All other info (album artists, labels, ...) is simply kept the same.

Allow moderator and admin to merge albums

---

app/serializers/track_serializer.rb

This should make it easier to invalidate cached audio files, since the `audio_file_id` is tied to a file on disk - if the file changes, the id will change as well.
Fix #393
No additional tests added, since we don't test basic fields in the serializers

Include `audio_file_id` in `TrackSerializer`

---

app/models/rescan_runner.rb

No test, because I couldn't figure out how to create a file with such tags. I did test locally that the problem files I had scanned without issue.

Fix error if tags contain null byte(s)

---

app/controllers/tracks_controller.rb

Once the response is `commit`ted, the headers can't be edited anymore, which is exactly what we want in this case.
Unfortunately, this can't be added to the tests, because the way responses and `ActionController::Live` work in tests just doesn't allow it (in fact, the tests already "test" for the presence of this header, and the tests still succeed even though in production the header is not present).
Fixes #503.

Make sure that content-length header can never be deleted

---

Gemfile
Gemfile.lock
gemset.nix

This adds [`ruby-lsp`](https://github.com/Shopify/ruby-lsp) to the development gems, so we can easily have syntax highlighting, better autocomplete, ...
I'd want to include this gem explicitly, since its usual editor integration doesn't work (well) with nix-based devshells (since it still needs to add a dependency to the PATH).

Add `ruby-lsp` to development gems

---

config/routes.rb

This PR adds the default rails health check as an endpoint in the routes. This allows us to setup some kind of uptime monitoring, without calling any of our actual controllers. In theory, we could also have clients (especially those with an audio cahce) check this before making any actual requests for new data.
From [the docs](https://api.rubyonrails.org/classes/Rails/HealthController.html):
> This endpoint will return a 200 status code if the app has booted with no exceptions, and a 500 status code otherwise.
Example request:
```sh
$ curl localhost:3000/api/up --verbose             
*   Trying [::1]:3000...
* Connected to localhost (::1) port 3000
> GET /api/up HTTP/1.1
> Host: localhost:3000
> User-Agent: curl/8.4.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< x-frame-options: SAMEORIGIN
< …
```

Enable rails health check in routes

---

Gemfile
Gemfile.lock

It would be nice to have the release notes for rubocop updates in Dependabot's PRs, and we would still want to use it even if we remove the other more specialized sets of cops.

Add rubocop explicitly as a dependency

---

app/serializers/album_serializer.rb
app/serializers/artist_serializer.rb

Our current usage of `resize_to_fit` doesn't really fit the way we display images. We are guaranteed a the maximum of the biggest dimension, but this means we can't be sure of the size of the smallest dimension. We places these images in cards where assume that they can be shown at ± the dimensions of the resize. This can result in low quality results when the image has a high aspect ratio. 
For example: I recently added an image that has a ratio of 3/1 , this is 500px x 167px after using `resize_to_fit: [500, 500]`. If this is displayed at 500px/500px, the image won't be shown at a decent quality. If we use `resize_to_cover: [500, 500]` the result will be 1500px x 500px, so it can be safely placed in a 500px/500px container. (This was sadly the only image provided as album artwork.)
Two …

Use `resize_to_cover` instead of `resize_to_fit` for all images

---

app/controllers/auth_tokens_controller.rb
app/models/auth_token.rb
app/policies/auth_token_policy.rb
app/serializers/auth_token_serializer.rb
db/migrate/20240817081958_add_application_to_auth_tokens.rb
db/schema.rb
test/factories/auth_tokens.rb
test/models/auth_token_test.rb

While working on a separate frontend app, I noticed that we use the `user_agent` attribute a bit inconsistent. For browser apps we track the actual user agent, but for native apps we use this to track the device info and the app info. 
A user can't currently distinguish two browser apps in their auth tokens, since they both just show the user agent string.
This PR allows us to separately track the application and the device/OS that is used for the auth token. I'd propose that:
* `application` is for the app and its version. Eg. `Accentor 0.14.1 on android`, `web 0.1.2`, ... 
* `user_agent` is for the device/OS/browser used. For browser apps this can remain the same, for native apps it could be something like `macOS 14.5 (Build 23F79)` or `Android 13 on Fairphone 4`
For both of these, I …

Add optional `application` attribute to auth tokens

---

app/models/audio_file.rb
test/models/audio_file_test.rb

This was only used in a migration, and new deployments will not actually need it.

Remove obsolete `check_file_attributes` method

---

app/models/audio_file.rb

This fixes an issue from #644 where our `AudioFile#convert` would return before ffmpeg finishes.
There are a few other ways to accomplish the same thing, but an empty block with a clear note
I did a manual test with the biggest audio file on my computer (1h20), so I could clearly see the effect of these changes

Make sure we wait for ffmpeg to finish when transcoding

---

app/jobs/create_transcoded_item_job.rb
app/models/audio_file.rb
test/controllers/tracks_controller_test.rb
test/jobs/create_transcoded_item_job_test.rb
test/models/audio_file_test.rb
test/test_helper.rb

Transcode to a temporary file which is only moved when finished

---

app/controllers/tracks_controller.rb

Since we never do live transcoding anymore, we can simplify the way we send
audio data to clients a lot. We can remove the usage of `ActionController::Live`
and don't have to do any manual copying to and from streams, all by just
switching back to Rack::Files.
Fixes #649.

Refactor sending audio in TracksController by switching back to Rack::Files

---

flake.nix

In production, memory usage of the server can be steadily increased by performing an activestorage request in an infinite loop. The issue can be reproduced in development (though it is less pronounced)
When using a ruby configured with jemalloc, the issue is no longer reproducible in development. So I'm hoping that the same will be true in production.

Use ruby that supports jemalloc

---

app/controllers/application_controller.rb
app/controllers/auth_tokens_controller.rb
app/models/auth_token.rb
test/controllers/auth_tokens_controller_test.rb
test/test_helper.rb

This PR switched our authentication method from with our device_id and secret to [rails' `generates_token_for`](https://api.rubyonrails.org/classes/ActiveRecord/TokenFor/ClassMethods.html#method-i-generates_token_for).
To avoid clients having to switch immediately, we send the token as if it was the secret and accept the `x-secret` header (or secret param). We also still allow clients to pass the device_id and secret.
My biggest reason for changing is performance. Every api request currently has to go through authentication. In our current implementation, we have to go through bcrypt to check the secret. By switching to `generates_token_for` we only have to check that the signature matches. Considering the amount a requests a user will send to get all albums, artists, tracks, plays, ... …

Switch to signed token to authenticate users

---

app/controllers/albums_controller.rb
app/controllers/artists_controller.rb
app/controllers/auth_tokens_controller.rb
app/controllers/codec_conversions_controller.rb
app/controllers/codecs_controller.rb
app/controllers/cover_filenames_controller.rb
app/controllers/genres_controller.rb
app/controllers/image_types_controller.rb
app/controllers/labels_controller.rb
app/controllers/locations_controller.rb
app/controllers/playlists_controller.rb
app/controllers/plays_controller.rb
app/controllers/tracks_controller.rb
app/controllers/users_controller.rb
test/controllers/albums_controller_test.rb
test/controllers/artists_controller_test.rb
test/controllers/auth_tokens_controller_test.rb
test/controllers/codec_conversions_controller_test.rb
test/controllers/codecs_controller_test.rb
test/controllers/cover_filenames_controller_test.rb
test/controllers/genres_controller_test.rb
test/controllers/image_types_controller_test.rb
test/controllers/labels_controller_test.rb
test/controllers/locations_controller_test.rb
test/controllers/playlists_controller_test.rb
test/controllers/plays_controller_test.rb
test/controllers/tracks_controller_test.rb
test/controllers/users_controller_test.rb

The status `unprocessable_entity` is deprecated (and not actual name of the 422 response) and will be removed in a future version of rack ([rack](https://github.com/rack/rack/blob/fac9a7a6cf01be691245947dab9fc9d3861230e1/lib/rack/utils.rb#L570), [mdn](https://developer.mozilla.org/en-US/docs/Web/HTTP/Reference/Status/422)).

Replace `unprocessable_entity` with `unprocessable_content`
